export type ToolDefinition = { slug:string; name:string; category:string; description:string; placeholder:string; system:string; keywords:string[] };

export const toolDefinitions:ToolDefinition[]=[
{slug:"ai-business-tools",name:"AI Business Tools",category:"Business",description:"Turn a business objective into structured, actionable ideas, positioning and execution steps.",placeholder:"Describe your business objective, product, audience or challenge...",system:"Act as a practical senior business strategist. Produce concise, structured, implementation-ready output based only on the user's context.",keywords:["ai business tools","business ai generator","ai business assistant"]},
{slug:"seo-keyword-generator",name:"SEO Keyword Generator",category:"SEO",description:"Generate keyword clusters, search-intent directions and content opportunities for organic discovery.",placeholder:"Enter a topic, product, service or target market...",system:"Act as a senior SEO strategist. Generate useful keyword clusters grouped by search intent, funnel stage and content opportunity. Avoid invented search volumes.",keywords:["seo keyword generator","ai keyword generator","ai seo tools"]},
{slug:"youtube-title-generator",name:"YouTube Title Generator",category:"Content",description:"Create stronger YouTube title concepts around audience promise, clarity, curiosity and search intent.",placeholder:"Describe the video topic, audience and key promise...",system:"Act as an expert YouTube packaging strategist. Generate distinct title options balancing clarity, curiosity and truthful audience promise. Do not use misleading clickbait.",keywords:["youtube title generator","ai youtube title generator","youtube ai tools"]},
{slug:"ai-marketing-copy",name:"AI Marketing Copy",category:"Marketing",description:"Create campaign angles, offers, headlines and conversion-oriented marketing messaging.",placeholder:"Describe the offer, audience, channel and desired action...",system:"Act as a senior direct-response and brand copy strategist. Produce persuasive but truthful marketing copy aligned to the audience, offer and channel.",keywords:["ai marketing copy","ai copy generator","marketing copy generator"]},
{slug:"startup-name-generator",name:"Startup Name Generator",category:"Business",description:"Explore brandable startup, company and product naming directions with positioning rationale.",placeholder:"Describe the product, market, brand personality and naming constraints...",system:"Act as a brand naming strategist. Generate distinctive, pronounceable naming directions with brief rationale. Do not claim trademark or domain availability.",keywords:["startup name generator","business name generator ai","ai company name generator"]},
{slug:"prompt-builder",name:"AI Prompt Builder",category:"Productivity",description:"Turn a rough objective into a clearer reusable prompt with context, constraints and output structure.",placeholder:"Describe what you want the AI to accomplish...",system:"Act as a prompt engineering specialist. Convert the user's goal into a reusable prompt with role, objective, context, constraints, quality criteria and output format.",keywords:["ai prompt builder","prompt generator","prompt engineering tool"]}
];

export function getTool(slug:string){return toolDefinitions.find(t=>t.slug===slug)}
