export type UseCase = { slug:string; title:string; description:string; audience:string; outcomes:string[]; workflows:string[]; keywords:string[] };

export const useCases:UseCase[]=[
{slug:"small-business",title:"AI Tools for Small Business",description:"Practical AI workflows for small businesses that need faster marketing, customer communication, content and everyday execution without adding headcount.",audience:"Owners, operators and lean teams",outcomes:["Create customer-ready marketing copy faster","Turn rough ideas into structured campaigns","Reduce repetitive writing and planning work"],workflows:["Marketing copy and offers","Email and customer communication","Local SEO and content planning","Business idea validation"],keywords:["ai tools for small business","small business ai tools","ai marketing tools"]},
{slug:"seo-teams",title:"AI Tools for SEO Teams",description:"AI-assisted workflows for keyword research, briefs, metadata, content planning and repeatable SEO production.",audience:"SEO specialists, agencies and content teams",outcomes:["Accelerate keyword and topic discovery","Standardize SEO briefs and metadata","Build repeatable organic-content workflows"],workflows:["Keyword ideation","Meta title and description generation","Content briefs","Internal-link planning"],keywords:["ai seo tools","seo ai tools","ai keyword generator"]},
{slug:"content-marketing",title:"AI Tools for Content Marketing",description:"Plan, draft and repurpose useful content across campaigns, landing pages, newsletters and social channels.",audience:"Content marketers and brand teams",outcomes:["Increase content throughput","Repurpose one idea across multiple formats","Keep messaging aligned to a campaign objective"],workflows:["Campaign ideation","Blog and landing-page outlines","Newsletter drafts","Content repurposing"],keywords:["ai content marketing tools","ai content generator","marketing ai tools"]},
{slug:"youtube-creators",title:"AI Tools for YouTube Creators",description:"Generate stronger video concepts, titles, hooks, descriptions and supporting promotional copy for YouTube workflows.",audience:"Creators, channels and video teams",outcomes:["Generate more title and hook options","Package videos around a clear audience promise","Speed up description and promotion workflows"],workflows:["YouTube title generation","Video hooks","Descriptions","Promotion copy"],keywords:["youtube ai tools","youtube title generator","ai tools for youtubers"]},
{slug:"ecommerce",title:"AI Tools for Ecommerce",description:"Create clearer product messaging, campaign concepts, promotional copy and customer-facing content for online stores.",audience:"Store owners, ecommerce marketers and growth teams",outcomes:["Improve product copy consistency","Launch promotions faster","Generate more campaign angles"],workflows:["Product descriptions","Offer positioning","Ad copy","Lifecycle email ideas"],keywords:["ai tools for ecommerce","ecommerce ai tools","ai product description generator"]},
{slug:"startup-founders",title:"AI Tools for Startup Founders",description:"Move from rough concept to clearer positioning, naming, messaging, customer discovery and go-to-market execution.",audience:"Founders and early-stage startup teams",outcomes:["Clarify positioning and value propositions","Generate naming and messaging options","Structure launch and validation tasks"],workflows:["Startup naming","Business idea development","Value proposition writing","Launch messaging"],keywords:["ai tools for startups","ai tools for founders","startup name generator"]},
{slug:"sales-teams",title:"AI Tools for Sales Teams",description:"Create prospecting messages, follow-ups, value propositions and repeatable sales communication faster.",audience:"Sales professionals, founders and revenue teams",outcomes:["Draft outreach more efficiently","Adapt messaging to different audiences","Reduce repetitive follow-up writing"],workflows:["Cold outreach","Follow-up sequences","Sales propositions","Objection-response drafts"],keywords:["ai sales tools","ai tools for sales","ai cold email generator"]},
{slug:"social-media",title:"AI Tools for Social Media",description:"Generate campaign ideas, captions, hooks and content variations for faster social media execution.",audience:"Social media managers, creators and agencies",outcomes:["Create more content variations","Turn campaign ideas into platform-ready copy","Reduce blank-page time"],workflows:["Caption generation","Hooks","Campaign ideas","Content calendars"],keywords:["ai social media tools","ai caption generator","social media ai tools"]},
{slug:"real-estate",title:"AI Tools for Real Estate",description:"Create property marketing copy, listing ideas, local-content angles and follow-up communication for real-estate workflows.",audience:"Agents, brokers and real-estate marketing teams",outcomes:["Draft listings faster","Generate local marketing ideas","Improve consistency in prospect follow-up"],workflows:["Property descriptions","Social promotion","Lead follow-up","Local content ideas"],keywords:["ai tools for real estate","real estate ai tools","ai listing description"]},
{slug:"agencies",title:"AI Tools for Marketing Agencies",description:"Standardize repeatable creative, SEO, copy and campaign workflows across multiple client accounts.",audience:"Digital agencies and client-service teams",outcomes:["Increase delivery speed","Standardize common deliverables","Generate more campaign alternatives per client"],workflows:["Client campaign concepts","SEO briefs","Ad and landing-page copy","Reporting narratives"],keywords:["ai tools for agencies","marketing agency ai tools","agency automation ai"]},
{slug:"freelancers",title:"AI Tools for Freelancers",description:"Use practical AI workflows to write proposals, create client content, plan projects and reduce administrative writing.",audience:"Freelancers and independent professionals",outcomes:["Respond to opportunities faster","Create client-ready drafts efficiently","Reduce repetitive admin work"],workflows:["Proposal drafts","Client emails","Content creation","Service positioning"],keywords:["ai tools for freelancers","freelancer ai tools","ai productivity for freelancers"]},
{slug:"productivity",title:"AI Tools for Productivity",description:"Turn notes and rough inputs into clearer plans, summaries, drafts and repeatable work outputs.",audience:"Professionals and knowledge workers",outcomes:["Reduce manual drafting","Structure unorganized information","Move from idea to usable output faster"],workflows:["Summaries","Planning","Rewriting","Task-oriented drafts"],keywords:["ai productivity tools","best ai tools for productivity","work productivity ai"]},
{slug:"email-marketing",title:"AI Tools for Email Marketing",description:"Generate subject lines, campaign angles, email drafts and lifecycle messaging for acquisition and retention.",audience:"Email marketers, ecommerce teams and founders",outcomes:["Create more subject-line variants","Accelerate campaign drafting","Adapt messaging across lifecycle stages"],workflows:["Subject lines","Promotional emails","Welcome campaigns","Re-engagement ideas"],keywords:["ai email marketing tools","ai email generator","email ai tools"]},
{slug:"local-business",title:"AI Tools for Local Business Marketing",description:"Create local offers, service-page ideas, review responses and promotional content for location-based businesses.",audience:"Clinics, restaurants, service businesses and local operators",outcomes:["Generate local campaign ideas","Create service-focused copy","Maintain faster customer communication"],workflows:["Local promotions","Service descriptions","Review-response drafts","Local SEO ideas"],keywords:["ai tools for local business","local business marketing ai","local seo ai tools"]},
{slug:"copywriting",title:"AI Tools for Copywriting",description:"Generate angles, headlines, benefit statements, calls to action and structured drafts for commercial writing.",audience:"Copywriters, marketers and founders",outcomes:["Explore more messaging angles","Draft conversion-focused structures faster","Turn product details into customer benefits"],workflows:["Headlines","Landing-page copy","Calls to action","Offer positioning"],keywords:["ai copywriting tools","ai copy generator","copywriting ai"]},
{slug:"entrepreneurs",title:"AI Tools for Entrepreneurs",description:"Practical AI support for ideas, positioning, marketing, research prompts and everyday business communication.",audience:"Entrepreneurs and owner-operators",outcomes:["Evaluate ideas faster","Create clearer commercial messaging","Accelerate daily business tasks"],workflows:["Business ideas","Marketing copy","Customer communication","Planning prompts"],keywords:["ai tools for entrepreneurs","entrepreneur ai tools","business ai tools"]}
];

export function getUseCase(slug:string){return useCases.find(item=>item.slug===slug)}
