export type UseCase = { slug:string; title:string; description:string; audience:string; outcomes:string[]; workflows:string[]; keywords:string[] };

export const useCases:UseCase[]=[
{slug:"small-business",title:"AI Tools for Small Business",description:"Practical AI workflows for small businesses that need faster marketing, customer communication, content and everyday execution without adding headcount.",audience:"Owners, operators and lean teams",outcomes:["Create customer-ready marketing copy faster","Turn rough ideas into structured campaigns","Reduce repetitive writing and planning work"],workflows:["Marketing copy and offers","Email and customer communication","Local SEO and content planning","Business idea validation"],keywords:["ai tools for small business","small business ai tools","ai marketing tools"]},
{slug:"seo-teams",title:"AI Tools for SEO Teams",description:"AI-assisted workflows for keyword research, briefs, metadata, content planning and repeatable SEO production.",audience:"SEO specialists, agencies and content teams",outcomes:["Accelerate keyword and topic discovery","Standardize SEO briefs and metadata","Build repeatable organic-content workflows"],workflows:["Keyword ideation","Meta title and description generation","Content briefs","Internal-link planning"],keywords:["ai seo tools","seo ai tools","ai keyword generator"]},
{slug:"content-marketing",title:"AI Tools for Content Marketing",description:"Plan, draft and repurpose useful content across campaigns, landing pages, newsletters and social channels.",audience:"Content marketers and brand teams",outcomes:["Increase content throughput","Repurpose one idea across multiple formats","Keep messaging aligned to a campaign objective"],workflows:["Campaign ideation","Blog and landing-page outlines","Newsletter drafts","Content repurposing"],keywords:["ai content marketing tools","ai content generator","marketing ai tools"]},
{slug:"youtube-creators",title:"AI Tools for YouTube Creators",description:"Generate stronger video concepts, titles, hooks, descriptions and supporting promotional copy for YouTube workflows.",audience:"Creators, channels and video teams",outcomes:["Generate more title and hook options","Package videos around a clear audience promise","Speed up description and promotion workflows"],workflows:["YouTube title generation","Video hooks","Descriptions","Promotion copy"],keywords:["youtube ai tools","youtube title generator","ai tools for youtubers"]},
{slug:"ecommerce",title:"AI Tools for Ecommerce",description:"Create clearer product messaging, campaign concepts, promotional copy and customer-facing content for online stores.",audience:"Store owners, ecommerce marketers and growth teams",outcomes:["Improve product copy consistency","Launch promotions faster","Generate more campaign angles"],workflows:["Product descriptions","Offer positioning","Ad copy","Lifecycle email ideas"],keywords:["ai tools for ecommerce","ecommerce ai tools","ai product description generator"]},
{slug:"startup-founders",title:"AI Tools for Startup Founders",description:"Move from rough concept to clearer positioning, naming, messaging, customer discovery and go-to-market execution.",audience:"Founders and early-stage startup teams",outcomes:["Clarify positioning and value propositions","Generate naming and messaging options","Structure launch and validation tasks"],workflows:["Startup naming","Business idea development","Value proposition writing","Launch messaging"],keywords:["ai tools for startups","ai tools for founders","startup name generator"]},
{slug:"sales-teams",title:"AI Tools for Sales Teams",description:"Create prospecting messages, follow-ups, value propositions and repeatable sales communication faster.",audience:"Sales professionals, founders and revenue teams",outcomes:["Draft outreach more efficiently","Adapt messaging to different audiences","Reduce repetitive follow-up writing"],workflows:["Cold outreach","Follow-up sequences","Sales propositions","Objection-response drafts"],keywords:["ai sales tools","ai tools for sales","ai cold email generator"]},
{slug:"social-media",title:"AI Tools for Social Media",description:"Generate campaign ideas, captions, hooks and content variations for faster social media execution.",audience:"Social media managers, creators and agencies",outcomes:["Create more content variations","Turn campaign ideas into platform-ready copy","Reduce blank-page time"],workflows:["Caption generation","Hooks","Campaign ideas","Content calendars"],keywords:["ai social media tools","ai caption generator","social media ai tools"]},
{slug:"real-estate",title:"AI Tools for Real Estate",description:"Create property marketing copy, listing ideas, local-content angles and follow-up communication for real-estate workflows.",audience:"Agents, brokers and real-estate marketing teams",outcomes:["Draft listings faster","Generate local marketing ideas","Improve consistency in prospect follow-up"],workflows:["Property descriptions","Social promotion","Lead follow-up","Local content ideas"],keywords:["ai tools for real estate","real estate ai tools","ai listing description"]},
{slug:"agencies",title:"AI Tools for Marketing Agencies",description:"Standardize repeatable creative, SEO, copy and campaign workflows across multiple client accounts.",audience:"Digital agencies and client-service teams",outcomes:["Increase delivery speed","Standardize common deliverables","Generate more campaign alternatives per client"],workflows:["Client campaign concepts","SEO briefs","Ad and landing-page copy","Reporting narratives"],keywords:["ai tools for agencies","marketing agency ai tools","agency automation ai"]},
{slug:"freelancers",title:"AI Tools for Freelancers",description:"Use practical AI workflows to write proposals, create client content, plan projects and reduce administrative writing.",audience:"Freelancers and independent professionals",outcomes:["Respond to opportunities faster","Create client-ready drafts efficiently","Reduce repetitive admin work"],workflows:["Proposal drafts","Client emails","Content creation","Service positioning"],keywords:["ai tools for freelancers","freelancer ai tools","ai productivity for freelancers"]},
{slug:"productivity",title:"AI Tools for Productivity",description:"Turn notes and rough inputs into clearer plans, summaries, drafts and repeatable work outputs.",audience:"Professionals and knowledge workers",outcomes:["Reduce manual drafting","Structure unorganized information","Move from idea to usable output faster"],workflows:["Summaries","Planning","Rewriting","Task-oriented drafts"],keywords:["ai productivity tools","best ai tools for productivity","work productivity ai"]},
{slug:"email-marketing",title:"AI Tools for Email Marketing",description:"Generate subject lines, campaign angles, email drafts and lifecycle messaging for acquisition and retention.",audience:"Email marketers, ecommerce teams and founders",outcomes:["Create more subject-line variants","Accelerate campaign drafting","Adapt messaging across lifecycle stages"],workflows:["Subject lines","Promotional emails","Welcome campaigns","Re-engagement ideas"],keywords:["ai email marketing tools","ai email generator","email ai tools"]},
{slug:"local-business",title:"AI Tools for Local Business Marketing",description:"Create local offers, service-page ideas, review responses and promotional content for location-based businesses.",audience:"Clinics, restaurants, service businesses and local operators",outcomes:["Generate local campaign ideas","Create service-focused copy","Maintain faster customer communication"],workflows:["Local promotions","Service descriptions","Review-response drafts","Local SEO ideas"],keywords:["ai tools for local business","local business marketing ai","local seo ai tools"]},
{slug:"copywriting",title:"AI Tools for Copywriting",description:"Generate angles, headlines, benefit statements, calls to action and structured drafts for commercial writing.",audience:"Copywriters, marketers and founders",outcomes:["Explore more messaging angles","Draft conversion-focused structures faster","Turn product details into customer benefits"],workflows:["Headlines","Landing-page copy","Calls to action","Offer positioning"],keywords:["ai copywriting tools","ai copy generator","copywriting ai"]},
{slug:"entrepreneurs",title:"AI Tools for Entrepreneurs",description:"Practical AI support for ideas, positioning, marketing, research prompts and everyday business communication.",audience:"Entrepreneurs and owner-operators",outcomes:["Evaluate ideas faster","Create clearer commercial messaging","Accelerate daily business tasks"],workflows:["Business ideas","Marketing copy","Customer communication","Planning prompts"],keywords:["ai tools for entrepreneurs","entrepreneur ai tools","business ai tools"]},
{slug:"saas",title:"AI Tools for SaaS Companies",description:"AI workflows for SaaS positioning, onboarding, lifecycle messaging, feature communication and growth content.",audience:"SaaS founders, product marketers and growth teams",outcomes:["Clarify product positioning","Create onboarding and lifecycle drafts faster","Generate feature and campaign messaging"],workflows:["SaaS landing-page copy","Feature announcements","Onboarding emails","Growth campaign ideas"],keywords:["ai tools for saas","saas ai tools","ai for saas marketing"]},
{slug:"b2b-marketing",title:"AI Tools for B2B Marketing",description:"Create sharper B2B positioning, demand-generation ideas, campaign briefs, sales enablement and account-focused messaging.",audience:"B2B marketers and revenue teams",outcomes:["Accelerate campaign planning","Align marketing and sales messaging","Generate account-specific content angles"],workflows:["Demand-generation campaigns","Case-study outlines","Sales enablement copy","Account-based messaging"],keywords:["ai tools for b2b marketing","b2b ai tools","ai marketing for b2b"]},
{slug:"customer-support",title:"AI Tools for Customer Support",description:"Draft helpful support responses, knowledge-base outlines, escalation summaries and consistent customer communication.",audience:"Customer support and success teams",outcomes:["Respond more consistently","Turn recurring questions into reusable guidance","Reduce manual support writing"],workflows:["Support reply drafts","FAQ creation","Knowledge-base outlines","Escalation summaries"],keywords:["ai tools for customer support","customer service ai tools","ai support response generator"]},
{slug:"human-resources",title:"AI Tools for HR Teams",description:"Support HR communication, role descriptions, onboarding materials, internal policies and employee-facing drafts.",audience:"HR leaders, recruiters and people teams",outcomes:["Draft HR communication faster","Standardize role and onboarding content","Reduce repetitive internal writing"],workflows:["Job descriptions","Onboarding checklists","Internal announcements","Policy outlines"],keywords:["ai tools for hr","hr ai tools","ai job description generator"]},
{slug:"recruiting",title:"AI Tools for Recruiters",description:"Create job posts, outreach messages, interview frameworks and candidate communication for faster recruiting workflows.",audience:"Recruiters and talent acquisition teams",outcomes:["Improve recruiting message consistency","Create role-specific outreach faster","Structure interview content"],workflows:["Job-post drafts","Candidate outreach","Interview questions","Follow-up communication"],keywords:["ai tools for recruiters","recruiting ai tools","ai recruiting assistant"]},
{slug:"consultants",title:"AI Tools for Consultants",description:"Turn client context into structured research questions, proposals, analyses, workshop outlines and executive-ready drafts.",audience:"Consultants and advisory professionals",outcomes:["Structure client problems faster","Create clearer deliverables","Reduce proposal and workshop preparation time"],workflows:["Proposal outlines","Discovery questions","Workshop agendas","Executive summaries"],keywords:["ai tools for consultants","consulting ai tools","ai for consultants"]},
{slug:"project-management",title:"AI Tools for Project Managers",description:"Structure project plans, risk notes, status updates, meeting outputs and stakeholder communication with focused AI workflows.",audience:"Project and program managers",outcomes:["Turn notes into structured updates","Improve stakeholder communication","Accelerate planning documentation"],workflows:["Project briefs","Status reports","Risk summaries","Meeting follow-ups"],keywords:["ai tools for project managers","project management ai tools","ai project planning"]},
{slug:"restaurants",title:"AI Tools for Restaurants",description:"Create local promotions, menu descriptions, social posts, review responses and customer communication for restaurant marketing.",audience:"Restaurant owners and hospitality marketers",outcomes:["Launch local promotions faster","Improve menu and campaign copy","Respond consistently to customer feedback"],workflows:["Menu descriptions","Local offers","Social media posts","Review responses"],keywords:["ai tools for restaurants","restaurant marketing ai","ai restaurant marketing tools"]},
{slug:"healthcare-marketing",title:"AI Tools for Healthcare Marketing",description:"Create educational marketing drafts, service-page structures, campaign concepts and patient-friendly communication for healthcare organizations.",audience:"Healthcare marketers and clinic operators",outcomes:["Create clearer service communication","Generate educational content ideas","Standardize marketing drafts"],workflows:["Service-page outlines","Educational content","Campaign ideas","Patient communication drafts"],keywords:["ai tools for healthcare marketing","healthcare ai marketing tools","ai for clinic marketing"]},
{slug:"education",title:"AI Tools for Education Teams",description:"Create course outlines, learning-content drafts, communication templates and program marketing for education workflows.",audience:"Educators, course creators and education teams",outcomes:["Structure learning materials faster","Create clearer program communication","Generate reusable teaching-content drafts"],workflows:["Course outlines","Lesson ideas","Student communication","Program marketing"],keywords:["ai tools for education","education ai tools","ai tools for teachers"]},
{slug:"coaches",title:"AI Tools for Coaches",description:"Build program positioning, session outlines, client communication, educational content and lead-generation messaging.",audience:"Coaches, mentors and independent experts",outcomes:["Clarify offers and programs","Create client content faster","Generate consistent lead-nurture communication"],workflows:["Offer positioning","Session outlines","Email nurture","Social content"],keywords:["ai tools for coaches","coaching ai tools","ai for online coaches"]},
{slug:"nonprofits",title:"AI Tools for Nonprofits",description:"Support fundraising communication, campaign messaging, volunteer outreach, impact storytelling and grant-related drafting.",audience:"Nonprofit teams and mission-driven organizations",outcomes:["Create fundraising drafts faster","Improve impact storytelling","Standardize volunteer and donor communication"],workflows:["Fundraising emails","Campaign narratives","Volunteer outreach","Grant-draft outlines"],keywords:["ai tools for nonprofits","nonprofit ai tools","ai fundraising tools"]},
{slug:"financial-services-marketing",title:"AI Tools for Financial Services Marketing",description:"Create educational content, campaign briefs, product messaging and customer communication for financial-services marketing teams.",audience:"Financial-services marketers and content teams",outcomes:["Structure complex topics clearly","Generate compliant-review-ready first drafts","Accelerate campaign ideation"],workflows:["Educational content outlines","Campaign briefs","Product messaging","Customer email drafts"],keywords:["ai tools for financial services marketing","finance marketing ai tools","ai financial content tools"]},
{slug:"developers",title:"AI Tools for Developer Productivity",description:"Use structured AI workflows for documentation, technical explanations, release communication and development planning.",audience:"Developers, engineering leads and technical teams",outcomes:["Draft technical documentation faster","Explain implementation details clearly","Improve release and planning communication"],workflows:["Documentation drafts","Release notes","Technical summaries","Implementation planning"],keywords:["ai tools for developers","developer productivity ai","ai developer tools"]},
{slug:"product-managers",title:"AI Tools for Product Managers",description:"Turn customer insights and product context into clearer requirements, launch messaging, research plans and stakeholder updates.",audience:"Product managers and product operations teams",outcomes:["Structure requirements faster","Synthesize product context","Accelerate launch and stakeholder communication"],workflows:["Product briefs","Research questions","Launch messaging","Stakeholder updates"],keywords:["ai tools for product managers","product management ai tools","ai product manager"]}
];

export function getUseCase(slug:string){return useCases.find(item=>item.slug===slug)}
