import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getUseCase, useCases } from "../data";

export function generateStaticParams(){return useCases.map(item=>({slug:item.slug}))}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const item=getUseCase(slug);if(!item)return {};return {title:item.title,description:item.description,keywords:item.keywords,alternates:{canonical:`/use-cases/${item.slug}`},openGraph:{title:item.title,description:item.description,url:`https://axionaihub.com/use-cases/${item.slug}`,type:"article"}}}

export default async function UseCasePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=getUseCase(slug);if(!item)notFound();const schema={"@context":"https://schema.org","@type":"WebPage",name:item.title,description:item.description,url:`https://axionaihub.com/use-cases/${item.slug}`,about:item.keywords};return <main className="page-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="section-heading"><span className="eyebrow">{item.audience}</span><h1>{item.title}</h1><p>{item.description}</p><div className="hero-actions"><Link className="button primary" href="/tools">Explore AI tools</Link><Link className="button secondary" href="/use-cases">All use cases</Link></div></section><section className="card-grid"><article className="feature-card"><h2>What this workflow helps you improve</h2><ul className="feature-list">{item.outcomes.map(value=><li key={value}>{value}</li>)}</ul></article><article className="feature-card"><h2>Common workflows</h2><ul className="feature-list">{item.workflows.map(value=><li key={value}>{value}</li>)}</ul></article><article className="feature-card"><h2>How to use AXION</h2><p>Start with a specific task, add the audience and desired outcome, choose the closest tool, then refine the generated result with concrete constraints. Focused input produces more useful output than a generic request.</p></article></section><section className="cta-band"><div><span className="eyebrow">Practical AI</span><h2>Move from a blank page to a usable first version faster.</h2></div><Link className="button light" href="/tools">Open the tool directory</Link></section></main>}
